### ISSUE TITLE
Crear refactor del api crud

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/cumplidos_crud#1]
Hacer refactor del api segun los lineamientos establecidos por la OAS

https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/control_error_json_crud.md

**Comment by anndresfelipe29** [comment]
- Se crea el crud correspondiente al esquema de cumplidos.
- Se dockeriza el crud acompañado de una bd local.
- Se refactoriza el api crud.
- Se hacen las migraciones del esquema y tablas parametricas.
