### ISSUE TITLE
Actualizar almacenamiento de documentos  en nuxeo con el api Documentos_crud.

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/cumplidos_crud#13]
https://github.com/udistrital/documentos_crud

**Comment by diagutierrezro** [comment]
Se realiza la actualización del cliente de cumplidos el cual ahora apunta hacia el API https://github.com/udistrital/documentos_crud y donde se almacenará la información de los cumplidos y el uid del documento en nuxeo, los cambios se pueden ver en el siguiente commit: https://github.com/udistrital/cumplidos_cliente/commit/1b8a540d3708d4fa5ca8eff85804c258232381ad
