### ISSUE TITLE
Construir el modelo de la base de datos

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/cumplidos_crud#14]
Diseñar e implementar el modelo de bd para almacenar las información ingresada en los informes de gestión y certificado de cumplimiento

**Comment by JuanCamiloMartinezLopez** [comment]
Se comienza con diseño del modelo de base de datos que se almacenara la informacion propia del informe de gestión y certificado de cumplimiento, referente al mes, año y contrato de este, por lo que se propone el siguiente formato.
![informe_modelo_db](https://user-images.githubusercontent.com/42418412/132692936-95675bb1-5aff-41e0-a0ea-1e4bff81126f.png)
se espera la reunión con el ingeniero Jhon para la aprobación o corrección del modelo

**Comment by JuanCamiloMartinezLopez** [comment]
El Ingeniero Jhon da visto bueno del modelo, también se añaden cambios como la columna **documento_contratista **y **proceso**
![informe_modelo_db](https://user-images.githubusercontent.com/42418412/132967203-ae5e100c-dcb2-49c3-884e-a573c94342f1.png)
Cambien se sugirió hacer uso de una base de datos no relacional, específicamente MongoDB

**Comment by blacburn** [comment]
Buen día, 

Se realiza validación del modelo planteado por parte del equipo de Base de datos, se indica que el mismo se encuentra acorde a los lineamientos de la OAS,

Se aprueba el modelo .

Gracias.

**Comment by JuanCamiloMartinezLopez** [comment]
Debido a los cambios respecto a solicitar las actividades especificas, se añade la tabla actividades_especificas para almacenar temporalmente mientras el sistema de **necesidades** esta listo para consultar las actividades especificas del contrato
![informe_modelo_db](https://user-images.githubusercontent.com/42418412/136123199-7ab02d2d-de29-41bd-8eaf-008d3dc15fed.png)
