### ISSUE TITLE
Construcción del modelo de la BD (Creación de Scripts)

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_crud#16]
Se debe realizar la creación de Scripts necesarios, según lo establecido en el [Diseño del modelo para la Base de Datos](https://github.com/udistrital/cumplidos_crud/issues/15).

**Nota**: indicar su terminación de forma oportuna para realizar la solicitud de carga correspondiente al DBA encargado.

**Comment by JuanCamiloMartinezLopez** [comment]
### Creación de la migración
Se crea la migración para la creación del esquema **infomre_gestion**, encargado de la almacenar la informacion de los informes, la estructura se hace conforme al modelo aprobado #14 .
Se hacen algunos cambios que son  conformes a los cambios en el formato
