### ISSUE TITLE
Pruebas unitarias para el api crud

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/cumplidos_crud#2]
Realizar las pruebas unitarias correspondientes según los lineamientos establecidos por la OAS 

https://github.com/udistrital/lineamientos_oas/blob/master/pruebas_unitarias_api_beego/crud_test.md

Se adjunta un documento con las pruebas realizadas al sistema Argo que pueden servir como guia
https://docs.google.com/document/d/1NyTf19triOaQgnX5KzICvtV0zJawxH7H-Fml7BSNpXM/edit

**Comment by anndresfelipe29** [comment]
Se crean y ejecutan las pruebas usando godog. Se hacen pruebas para las transacciones masivas, un escenario por transaccion y 3 pruebas por escenario.

Para ejecutarlas se usa el comando CUMPLIDOS_CRUD_HTTP_PORT="variable" CUMPLIDOS_CRUD_PGUSER="variable" CUMPLIDOS_CRUD_PGPASS="variable" CUMPLIDOS_CRUD_RUN_MODE=dev CUMPLIDOS_CRUD_PGHOST="variable" CUMPLIDOS_CRUD_PGDB="variable" CUMPLIDOS_CRUD_PGSCHEMA="variable" godog

A continuación se muestran los resultados de las pruebas:

![image](https://user-images.githubusercontent.com/30865375/100644765-b9ceeb80-3309-11eb-823f-336b2a8fd502.png)

![image](https://user-images.githubusercontent.com/30865375/100644803-c6ebda80-3309-11eb-89eb-6a75c3aa9292.png)

![image](https://user-images.githubusercontent.com/30865375/100644821-ce12e880-3309-11eb-9ed8-f945bd27d481.png)
