### ISSUE TITLE
Revision de migraciones del api crud

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/cumplidos_crud#3]
Realizar migraciones del api crud según lineamientos de la OAS

https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/beego_migrations.md

- [x] Migración para la creación de la bd
- [x] Migración de tablas paramétricas

**Comment by diagutierrezro** [comment]
Se agregan dos migraciones de la base de datos según los lineamientos de la OAS:

- La primera migración realiza la creación del esquema junto con las tablas de cumplidos y sus relaciones.
- La segunda migración realiza un llenado de las dos tablas paramétricas de la base de datos (item_informe y estado_pago_mensual).

_Estas migraciones se encuentran en el repositorio del crud de cumplidos en la carpeta database_
